### ISSUE TITLE
Support light and dark mode

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/discourse-theme#5]
Currently we only have a dark mode, which confusingly registers itself as light mode in some UI fields. We should look into providing two custom Color Schemes: Godot Light and Godot Dark

**Comment by winston-yallow** [comment]
@mariomadproductions just to clarify from the closed issue: Would a light color scheme be enough for you, or do you also want the option for different themes? DIfferent themes is a bit more work to support for us though

**Comment by mariomadproductions** [comment]
> @mariomadproductions just to clarify from the closed issue: Would a light color scheme be enough for you (with the current theme), or do you also want the option for different themes? DIfferent themes is a bit more work to support for us though

Just a light color scheme would be great.

**Comment by fantomac** [comment]
Hi, perhaps we can contribute to propose new themes if you share the style sheet.
Have a nice day !

**Comment by winston-yallow** [comment]
Hi @fantomac, that's exactly what this repository is. If you want to contribute you'll need to learn how discourse theming works and then make a pull request to this repository. Be sure to test it before submitting anything by using the official discourse theme creator site. You can register there and preview your theme.
